linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - nlreturn
    - wsl

linters-settings:
  lll:
    line-length: 140
  tagliatelle:
    case:
      rules:
        yaml: snake
