name: Go

on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make check cover
      - name: Upload coverage
        uses: codecov/codecov-action@v2
